# Generated by Django 4.1.2 on 2022-10-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['created_at'], 'verbose_name': 'Температура', 'verbose_name_plural': 'Температуры'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Сенсор', 'verbose_name_plural': 'Сенсоры'},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='sencor',
            new_name='sensor',
        ),
    ]
